### ISSUE TITLE
Can create_report show labels instead of variable names for labelled data?

### ISSUE THREAD

**Issue by NatalieSoto** [boxuancui/DataExplorer#101]

**Comment by boxuancui** [comment]
@NatalieSoto Could you be more specific? and which part of `create_report` are you referring to?

**Comment by NatalieSoto** [comment]
Sure, I apologize if my question wasn't really informative. I meant for the exploratory data analysis (Introduce, plot missing, plot_bar, plot_hist, plot_correlation). It doesn't have to be within create_report.
I work with datasets with over 500 variables with informative labels and shorter (and easier to work with) variable names. When exploring the data it would be useful to see the variable labels. I was wondering if there was any way this could be accomplished (maybe by combining the DataExplorer package with other packages like expss, or sjlabelled?)that I haven't found yet.  
Thank you!

**Comment by boxuancui** [comment]
Are these labels unique for each variable? If so, could you rename all your columns to these labels? If the labels are tag-based, you will have to process your data before plugging into DataExplorer.

In case I misunderstand your question, it will be extremely helpful if you can provide an example, ideally with reproducible code and data. Thanks!

**Comment by NatalieSoto** [comment]
They are unique, I just wanted to avoid renaming my columns to lengthy names. I guess this is the best way, though. Thank you!

**Comment by boxuancui** [comment]
One goal of DataExplorer is to get to the insights faster. I understand data can be messy, so what I usually do is to use each of the functions iteratively to get down to a smaller subset of variables of interest. Hope that helps!

**Comment by NatalieSoto** [comment]
It does, thank you!
