### ISSUE TITLE
Allow specification of report title?

### ISSUE THREAD

**Issue by langfob** [boxuancui/DataExplorer#103]
Would it be useful and easy to allow the user to specify their own report title in the call to `create_report`?  

I often have several analyses open at once but they all have the same title: "Data Profiling Report", which makes it harder to figure out which one I'm looking at.  

Currently, the title seems to be hard-coded in `rmd_template/report.rmd`.  I know that in an Rmd file I could print a variable title by saying:
```
params:
  mytitle: "whatever my title is"
title: "`r params$mytitle`"
```
So, could you 

- add a title argument to `create_report`  that defaults to "Data Profiling Report",
- pass the title variable in the params list that is handed to the `render` call inside `create_report`,
- modify the title command in the `report.rmd` file?  

That seems straightforward, but I'm also not expert enough to know if that would create some kind of security risk because R would be executing `params$mytitle`.  

In any case thanks a lot for creating this package.  It's very useful.

**Comment by boxuancui** [comment]
@langfob This is now available using `create_report(..., report_title = "My Fancy Report")`.

**Comment by langfob** [comment]
@boxuancui Great.  I couldn't find this option in any of the source code or the documentation or your wiki articles or the documentation for render.  It's exactly what I needed.  Thanks.
