### ISSUE TITLE
How to render multi page histograms (plot_histogram) graph in rshiny?

### ISSUE THREAD

**Issue by mdumer** [boxuancui/DataExplorer#104]
Hi,

hope you are doing well. i was exploring your library. During that, i tried only histograms on large number of columns (More then 16 Col) file. Histograms were generated in two pages.  when i render in shiny, It shows only 2nd page of Histograms.  So how can we render both pages of histograms in r shiny app?

Here is the simple example code of it.

```R
library(shiny)
library(DataExplorer)

ui <- fluidPage(
  plotOutput("plot")
)

server <- function(input, output, session) {
## df contains 18 columns
  output$plot <- renderPlot({plot_histogram(df)})
}

shinyApp(ui, server)
```

Thanks

**Comment by boxuancui** [comment]
You will have to split your data into multiple ones and call `plot_histogram` with each subset. E.g.,

```R
ui <- fluidPage(
  plotOutput("plot1"),
  plotOutput("plot2")
)

server <- function(input, output, session) {
  output$plot1 <- renderPlot({plot_histogram(df[, 1:9], nrow = 3L, ncol = 3L)})
  output$plot2 <- renderPlot({plot_histogram(df[, 10:18], nrow = 3L, ncol = 3L)})
}
```

**Comment by boxuancui** [comment]
@mdumer Did this solve your problem?

**Comment by mdumer** [comment]
its a static way of handling more than 18 columns data but we have to work for the dynamic solution.

I have tried this way for my learning

In shiny app every new dataframe has multiple columns so i checked each datafarme, divide number of cols by 9, from quotient and reminder i have generated multiple plots by using renderUI. 

i am fresher so i have used this way dont know either its a good way or not.

**Comment by boxuancui** [comment]
Yes, `renderUI` should be fine. That's what I usually do for dynamic plot generation.

**Comment by mdumer** [comment]
I Just got a little problem in this logic today. like DF has 10 or 17 columns. if i divide by 9 then reminder is 1, same as 16: reminder is 1. So the 9 and 16 graphs look good but remaining 1 graph is generated on a whole page. 

How can i generate that 1 graph in your grid shape. (3*3) or (4*4) ?

**Comment by boxuancui** [comment]
I don't think this is easily achievable. Maybe you could tweak your output width and height to fit 10 columns to a (3x4 or 4x3) grid? Or 3 pages of 2x2?

Similarly, 17 columns -> (4x5 or 5x4) or 2 pages of 3x3.
