### ISSUE TITLE
Getting an error with plot_bar

### ISSUE THREAD

**Issue by eyadsibai** [boxuancui/DataExplorer#105]
```
Error in gtable_add_grob(gt, grobs, t = positions$t, b = positions$b,  : 
  Not all inputs have either length 1 or same length same as 'grobs'
```

I am getting an error when trying to use plot_bar. When I plot just that particular column it works, but when I call plot_bar over the whole dataframe I get the error. If I remove that particular column it works with the whole dataframe.

**Comment by eyadsibai** [comment]
another question, if you select only one particular column and call `plot_bar` you will get a plot even if it is not a discrete feature, but it is not the case when you call it over a dataframe. I believe the behavior should be the same (by not plotting)

**Comment by boxuancui** [comment]
Could you share some re-producible code and data?

**Comment by eyadsibai** [comment]
I am trying to extract you a sample file, but when I remove other columns and keep only the columns that have issues it works! pretty strange

**Comment by eyadsibai** [comment]
it is worth mentioning that the column is string with fixed characters length (40 characters)

**Comment by boxuancui** [comment]
I assume this is related to #106, so closing.

**Comment by eyadsibai** [comment]
actually it is not, but since I cannot help you in reproducing it, it's ok to close it!

**Comment by boxuancui** [comment]
If you find a way to reproduce it, please re-open this issue. Thanks!
