### ISSUE TITLE
Error: object 'DataExplorer' not found

### ISSUE THREAD

**Issue by Andrzej-Andrzej** [boxuancui/DataExplorer#107]
I receive this error:
"Error: object 'DataExplorer' not found", after I have installed DataExplorer package from CRAN (with dependencies=TRUE) in RStudio version 1.2.1322. I tried removed, reinstall package etc.
No success.
Now, when I start RStudio I always receive this error:
Error: object 'DataExplorer' not found.

**Comment by boxuancui** [comment]
Do you see any error messages when installing the package? I doubt it is installed successfully. What is your R version?

**Comment by Andrzej-Andrzej** [comment]
Hi, I reinstalled Rstudio to newest version and the package and now seems to be OK. 
My R version is: 3.5.2. Thanks for your work.

**Comment by boxuancui** [comment]
Thanks for using DataExplorer!
