### ISSUE TITLE
introduce, plot_intro, plot_bar is not working with integer discrete values(Read as continuous value)

### ISSUE THREAD

**Issue by mdumer** [boxuancui/DataExplorer#110]
Hi,
Hope you are doing well. I tried this thing and find this issue.

> head(df)
  Churn VoiceMail
1     0              1
2     0              1
3     0              0
4     0              0
5     0              0
6     0              0

>introduce(df)
rows | 599
columns | 2
discrete_columns | 0
continuous_columns | 2
all_missing_columns | 0
total_missing_values | 0
complete_rows | 599
total_observations | 1198
memory_usage | 6152

>plot_intro(df)
![plot](https://user-images.githubusercontent.com/48059896/54522938-31bb7d80-4990-11e9-89d0-e6585f57ca9b.jpg)
 
Thanks

**Comment by boxuancui** [comment]
The package can only detect feature types by guessing. If you would like to set them as discrete values, you can simply do `update_columns(df, names(df), as.factor)`, and then run these functions again. I don't think it is possible to force define feature class outside its generic type. Hope this helps.
