### ISSUE TITLE
issue with create_report

### ISSUE THREAD

**Issue by nmarun** [boxuancui/DataExplorer#115]
`DataExplorer::create_report(as.data.table(train))` or `DataExplorer::create_report(train)` gives me the below error:

> label: principle_component_analysis
> Quitting from lines 208-221 (report.rmd) 
> Show Traceback
> 
> Rerun with Debug
> Error in value[[3L]](cond) : 
> Consider passing `na.omit(data)` as input.

**Comment by boxuancui** [comment]
If you have no prior knowledge about your data, consider creating the report without PCA:

```R
create_report(train, config = configure_report(add_plot_prcomp = FALSE)
```

If you are using the latest version, `create_report` has built-in treatment of missing data/incomplete rows. In addition, the error comes from [`plot_prcomp`](https://github.com/boxuancui/DataExplorer/blob/master/R/plot_prcomp.r#L45), so I suspect something is going on in your dataset that sneaked away from all the missing data treatment.

**Comment by nmarun** [comment]
I had to update a whole bunch of old packages, not just DataExplorer, but
your suggestion finally worked out. Thanks so much for your quick reply.
