### ISSUE TITLE
Suppress correlation values displayed using geom_text() in plot_correlation()

### ISSUE THREAD

**Issue by basil-isc** [boxuancui/DataExplorer#117]
Love the package.
But it is not clear whether it is possible to suppress the text displayed on the heatmap produced using plot_correlation(). Using plot_correlation() on the Nobel Prize dataset for this weeks Tidy Tuesday (https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-05-14) produces a dense plot. 

Since the text makes the plot very dense even when the number of categories are less than 20, is there any way to suppress the text?
![000023](https://user-images.githubusercontent.com/40520120/57698780-06919980-7674-11e9-9a36-820a5df4264d.png)

**Comment by boxuancui** [comment]
You can adjust the text size with `geom_text_args`, or simply turn them off, e.g.,
```R
plot_correlation(iris, geom_text_args = list(size = 0))
```
