### ISSUE TITLE
plot_prcomp error from create_report

### ISSUE THREAD

**Issue by mementonature** [boxuancui/DataExplorer#118]
Quitting from lines 204-217 (report.rmd) 
Error in data.table(pc = paste0("PC", seq_along(pca$sdev)), var = var_exp,  : 
  Item 2 has no length. Provide at least one item (such as NA, NA_integer_ etc) to be repeated to match the 1 row in the longest column. Or, all columns can be 0 length, for insert()ing rows into.

this is my data.frame including NA ins two columns

> summary(mydata)
>        ID     Nest.Random       Species        lat              long         beach_with   
>  N1     : 1   Nest  :19   Green     : 6   Min.   :-26.61   Min.   :153.1   Min.   : 1.90  
>  N10    : 1   Random:51   Loggerhead:64   1st Qu.:-26.56   1st Qu.:153.1   1st Qu.:12.71  
>  N11    : 1                               Median :-26.50   Median :153.1   Median :17.67  
>  N12    : 1                               Mean   :-26.50   Mean   :153.1   Mean   :19.50  
>  N13    : 1                               3rd Qu.:-26.44   3rd Qu.:153.1   3rd Qu.:23.39  
>  N14    : 1                               Max.   :-26.41   Max.   :153.1   Max.   :52.20  
>  (Other):64                                                                               
>   beach_slope       dune_width       dune_slope     dune_crest_height profile_curveture  
>  Min.   :-1.751   Min.   : 2.571   Min.   : 0.626   Min.   : 1.797    Min.   :-0.324000  
>  1st Qu.: 3.987   1st Qu.: 7.613   1st Qu.:12.859   1st Qu.: 5.546    1st Qu.:-0.010000  
>  Median : 5.420   Median : 9.969   Median :15.939   Median : 6.205    Median :-0.001500  
>  Mean   : 5.037   Mean   :11.808   Mean   :15.923   Mean   : 6.266    Mean   :-0.006371  
>  3rd Qu.: 6.282   3rd Qu.:14.635   3rd Qu.:18.637   3rd Qu.: 7.060    3rd Qu.: 0.006750  
>  Max.   :10.154   Max.   :38.869   Max.   :37.949   Max.   :10.543    Max.   : 0.111000  
>                                                                                          
>  terrain_ruggedness  Dist_to_veg     dist_to_sparse_veg Distance.to.urban  illuminance    
>  Min.   :0.00100    Min.   : 0.000   Min.   : 0.000     Min.   : 50.99    Min.   : 0.257  
>  1st Qu.:0.00625    1st Qu.: 1.180   1st Qu.: 0.283     1st Qu.: 90.45    1st Qu.: 1.624  
>  Median :0.01800    Median : 6.306   Median : 1.131     Median :142.07    Median : 3.203  
>  Mean   :0.03936    Mean   : 7.170   Mean   : 2.412     Mean   :177.64    Mean   : 3.830  
>  3rd Qu.:0.03900    3rd Qu.:10.400   3rd Qu.: 2.345     3rd Qu.:194.34    3rd Qu.: 5.314  
>  Max.   :0.46800    Max.   :33.121   Max.   :17.018     Max.   :597.23    Max.   :13.722  
>                                                                                           
>    nestlings       unhatched           Species2  hatched_percentage
>  Min.   : 70.0   Min.   :20.00   Green     : 6   Min.   :0.6897    
>  1st Qu.: 94.5   1st Qu.:24.00   Loggerhead:64   1st Qu.:0.7473    
>  Median :122.0   Median :26.00                   Median :0.8226    
>  Mean   :121.9   Mean   :27.84                   Mean   :0.8035    
>  3rd Qu.:144.0   3rd Qu.:30.50                   3rd Qu.:0.8529    
>  Max.   :200.0   Max.   :40.00                   Max.   :0.8889    
>  NA's   :51      NA's   :51                      NA's   :51

**Comment by boxuancui** [comment]
I believe there is something with the data, possibly not enough complete rows. You could verify this with `plot_intro(mydata)`.

If the data is raw, try removing `plot_prcomp` and run `create_report` again:

```R
create_report(mydata, config = configure_report(add_plot_prcomp = FALSE))
```

**Comment by boxuancui** [comment]
@mementonature Is your issue resolved?

**Comment by mementonature** [comment]
Sorry yes it is solved was my first theard

**Comment by mementonature** [comment]
thanks yes it is sry for not marke it as resolved, i am new to git hub

**Comment by boxuancui** [comment]
No worries! and you don't have to. I will close this issue then. Thanks for using DataExplorer.
