### ISSUE TITLE
create_report Quitting from lines 204-217 (report.rmd)

### ISSUE THREAD

**Issue by abigcleverdog** [boxuancui/DataExplorer#124]
newbie to data. I just used this package for the first time on the 'titanic survivor' dataset and:

create_report(full)
[full.zip](https://github.com/boxuancui/DataExplorer/files/3513910/full.zip)

> Error in data.table(pc = paste0("PC", seq_along(pca$sdev)), var = var_exp,  : 
>   Item 2 has no length. Provide at least one item (such as NA, NA_integer_ etc) to be repeated to match the 1 row in the longest column. Or, all columns can be 0 length, for insert()ing rows into. 
> 26.
> stop("Item ", i, " has no length. Provide at least one item (such as NA, NA_integer_ etc) to be repeated to match the ", 
>     nr, " row", if (nr > 1L) "s", " in the longest column. Or, all columns can be 0 length, for insert()ing rows into.") 

my data is attached.

**Comment by boxuancui** [comment]
Disable PCA for raw data:

```R
create_report(data, config = configure_report(add_plot_prcomp = FALSE))
```

Or disable scaling for PCA:

```R
create_report(data,
              config = configure_report(
                plot_prcomp_args = list(
                  prcomp_args = list(scale = FALSE)
                )
              )
)
```
