### ISSUE TITLE
eda?

### ISSUE THREAD

**Issue by victor-moreno** [boxuancui/DataExplorer#13]
Hi
Where is package "eda" that GenerateReport requires?

GenerateReport<-
function (input_data, output_file = "report.html", output_dir = getwd(), 
    ...) 
{
    report_dir <- system.file("rmd_template/report.rmd", package = "eda")

**Comment by boxuancui** [comment]
This is due to renaming the package from **eda** to **DataExplorer**. For now, please run the following code to replace the function:

```
GenerateReport <- function(input_data, output_file = "report.html", output_dir = getwd(), ...) {
  report_dir <- system.file("rmd_template/report.rmd", package = "DataExplorer") ## this line causes the bug
  render(input = report_dir,
         output_file = output_file,
         output_dir = output_dir,
         params=list(data = input_data, fun_options = list()),
         ...)
  browseURL(file.path(output_dir, output_file))
}
```

I will push a fix soon.

**Comment by boxuancui** [comment]
The bug is fixed on both master and develop. Feel free to install from GitHub:

```
if (!require(devtools)) install.packages("devtools")
library(devtools)
install_github("boxuancui/DataExplorer")
```

I will close this ticket when CRAN accepts the new version.

**Comment by boxuancui** [comment]
Version 0.2.4 is on CRAN now and the function should work as expected. Please re-open this ticket if you see any more issues.
