### ISSUE TITLE
unable to install the package

### ISSUE THREAD

**Issue by vidhirathod** [boxuancui/DataExplorer#131]
R restarts and still the package in not instantly with install.packages() command

**Comment by boxuancui** [comment]
Would you mind providing more information? `sessionInfo()`?

**Comment by vidhirathod** [comment]
Hey,

I was working on a data science project and needed some predefined
functions for EDA purpose.
I came to know about dataexplorer and tried to install...

I had to restart my machine to make it start working. Although, I still
cannot figure out how to use these:
plot_qq(diamonds)
Error in UseMethod("depth") :
  no applicable method for 'depth' applied to an object of class "NULL"
> plot_qq(diamonds, by = "cut")
Error in UseMethod("depth") :
  no applicable method for 'depth' applied to an object of class "NULL"

examples are from this link:
https://cran.r-project.org/web/packages/DataExplorer/readme/README.html
Thanks & Regards,
Vidhi Rathod
<http://www.facebook.com/vidhi.rathod.357>
<http://www.linkedin.com/hp/?dnr=cJ2qg35sxxbSBXR6K_g4l_EsIO6DkvSbKEIc>

**Comment by boxuancui** [comment]
Could you provide your session info? It is working fine for me.
