### ISSUE TITLE
 Error: missing value where TRUE/FALSE needed 

### ISSUE THREAD

**Issue by ericbrownaustin** [boxuancui/DataExplorer#136]
I am running into issues with both the qq_plot `label: plot_normal_qq Quitting from lines 159-166 (report.rmd) ` and the scatter_plot `Quitting from lines 249-256 (report.rmd) Error: missing value where TRUE/FALSE needed`

I'm not sure which columns are causing problems based on the errors.

**Comment by boxuancui** [comment]
Have you checked with `profile_missing` or `plot_missing` first? Maybe some features have everything missing. Without reproducible data, I don't know what would have caused the error.

**Comment by ericbrownaustin** [comment]
It looks like the issue was a constant variable I had in the data (used to differentiate between train and test data).  Once I removed the column it worked.  Adding a function to remove any constant variables prior to plotting or a new error would be a nice addition.

p.s. I love this package!
