### ISSUE TITLE
How to change this font-stype of a plot

### ISSUE THREAD

**Issue by jmxsy2016** [boxuancui/DataExplorer#140]
Thank you for your work! But I have met an issue:  How to change this font-stype of a plot? such as 'Times New Roman'. Thank you!

**Comment by boxuancui** [comment]
Take `plot_missing` for example (other plotting functions will be the same):

```R
library(DataExplorer)
library(ggplot2)

plot_missing(airquality,
             theme_config = list(
               text = element_text(family = "Times New Roman")
             ))
```

**Comment by jmxsy2016** [comment]
OK！Thank you，boxuancui
