### ISSUE TITLE
"unused argument" error in create_report

### ISSUE THREAD

**Issue by andrewcstewart** [boxuancui/DataExplorer#142]
I'm getting an error anytime I try to run create_report.  I thought it might just be my data.frame, but it turns out it is happening with any data.frame.

```
create_report(mtcars)

...

Quitting from lines 104-110 (report.rmd) 
Error in titleGrob(label, x, y, hjust = hj, vjust = vj, angle = angle,  : 
  unused argument (expand_y = TRUE)
```
Any ideas?

**Comment by boxuancui** [comment]
Hi @andrewcstewart , I can't reproduce this as it runs fine from my end. Would you mind providing your `sessionInfo()`?

**Comment by andrewcstewart** [comment]
Hey @boxuancui  - I'm actually suspecting this might be part of some broader issue of library corruption in my R installation that I'm starting to see.  I'll post back here if I still see the error after resolving my primary issue, but will close for now.
