### ISSUE TITLE
Fill colors in plot_boxplot

### ISSUE THREAD

**Issue by guilhermedossantos** [boxuancui/DataExplorer#147]
Hey, congrats on the great package!

I would like to be able to set fill colors in plot_boxplot according to the categories of the variable pessed to the argument "by". I know it is not that necessary since the labels of the categories are at one of the axes, but i think it would be a nice feature and also, it would be useful when presenting the data to an audience with no statistical background, for instance.

Thanks in advance and congratulations again for the package!

**Comment by boxuancui** [comment]
Hi @guilhermedossantos , I think that's a duplication of information. As a general package maintainer, I don't think I can add that as a feature. I have been especially careful when dealing with colors (#99 #113 #129), and would not add anything unnecessary.

With that said, you can always overwrite [this line](https://github.com/boxuancui/DataExplorer/blob/master/R/plot_boxplot.r#L65) to add fill color, e.g., `aes(x = by_f, y = value, fill = by_f)`.

**Comment by guilhermedossantos** [comment]
Hi! That's completely understandable, and thanks for the suggestion!
