### ISSUE TITLE
CRAN removal - re-upload?

### ISSUE THREAD

**Issue by pfistfl** [boxuancui/DataExplorer#148]
DataExplorer has been removed from [CRAN](https://cran.r-project.org/web/packages/DataExplorer/index.html)

We currently rely on it in the [mlr3gallery](https://github.com/mlr-org/mlr3gallery), so I wanted to ask if it will be re-uploaded anytime soon?

**Comment by boxuancui** [comment]
I am currently looking into it, and will provide a fix soon. Thanks and apologies for any inconvenience.

---

For anyone who is interested, reason for removal: https://cran-archive.r-project.org/web/checks/2020/2020-11-01_check_results_DataExplorer.html. Appreciate any ideas on how to address this.

> Version: 0.8.1
> Check: re-building of vignette outputs
> Result: WARN
>     Error(s) in re-building vignettes:
>      ...
>     --- re-building 'dataexplorer-intro.Rmd' using rmarkdown
>     corrupted size vs. prev_size
>     corrupted size vs. prev_size
>     Aborted
> Flavor: r-devel-linux-x86_64-debian-clang
> 
> Version: 0.8.1
> Check: re-building of vignette outputs
> Result: WARN
>     Error(s) in re-building vignettes:
>     --- re-building ‘dataexplorer-intro.Rmd’ using rmarkdown
>     corrupted size vs. prev_size
> Flavor: r-devel-linux-x86_64-fedora-clang

**Comment by pfistfl** [comment]
thanks for the awesome package and the fast response!

**Comment by boxuancui** [comment]
Update: I submitted v0.8.2, and is pending a manual inspection. I will follow up here with more news. Thank you for your patience everyone!

> Dear maintainer,
> 
> package DataExplorer_0.8.2.tar.gz has been auto-processed and is pending a manual inspection. A CRAN team member will typically respond to you within the next 5 working days. For technical reasons you may receive a second copy of this message when a team member triggers a new check.

**Comment by boxuancui** [comment]
**[Update]**
CRAN team is reporting a new error:

> Thanks, we see this still fails in vignettes:
> 
> Error(s) in re-building vignettes:
> --- re-building ‘dataexplorer-intro.Rmd’ using rmarkdown
> 
>   *** caught segfault ***
> address (nil), cause 'unknown'
> 
> Traceback:
>   1: fsort(as.numeric(irows))
>   2: `[.data.table`(dt, variable %in% feature_names[x])
>   3: dt[variable %in% feature_names[x]]
>   4: ggplot(dt[variable %in% feature_names[x]], aes(x = value))
>   5: FUN(X[[i]], ...)
>   6: lapply(X = X, FUN = FUN)
>   7: .lapply(parallel = parallel, X = layout, FUN = function(x) {
> ggplot(dt[variable %in% feature_names[x]], aes(x = value)) +
> do.call("geom_histogram", c(na.rm = TRUE, geom_histogram_args)) +
> do.call(paste0("scale_x_", scale_x), list()) + ylab("Frequency")})
>   8: plot_histogram(final_data, nrow = 3L, ncol = 3L)
> 
> which seems to be in data.table (but nothing else using data.table is failing in this way).
> 
> Can you confirm and perhaps ask the data.table maintainer in case you can confirm it is from data.table?

And I found something similar here: https://github.com/Rdatatable/data.table/issues/2707. Still talking to CRAN team about the submission. Thank you for your patience.

**Comment by boxuancui** [comment]
Still fails during re-submission. Asked in data.table: https://github.com/Rdatatable/data.table/issues/4819

**Comment by boxuancui** [comment]
Latest update: I am waiting for data.table 1.13.4 to be release onto CRAN in a few weeks. This then should be resolved and will be closed after that. See https://github.com/Rdatatable/data.table/issues/4819#issuecomment-732405901 for more details. Thank you all!

**Comment by boxuancui** [comment]
DataExplorer 0.8.2 is on CRAN now. Thank you for your patience!
