### ISSUE TITLE
Unable to install DataExplorer

### ISSUE THREAD

**Issue by statslady** [boxuancui/DataExplorer#151]
Hi,
I am trying to install this package in R and here is the code that I used. 
library(devtools)
devtools::install_github("boxuancui/DataExplorer", ref = "develop")

But this still does not work. 

Here is the error message that I get:

> devtools::install_github("boxuancui/DataExplorer", ref = "develop")
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘ellipsis’ 0.3.0 is already loaded, but >= 0.3.1 is required

Please advise.

Thanks!

**Comment by boxuancui** [comment]
You will need to update `‘ellipsis’` to 0.3.1 as the message suggests.

**Comment by statslady** [comment]
Thanks for your quick response. Yes, I have tried to do it but I am not sure what the following errors mean. I have tried SO as well but not seeing any specific resolutions for this error. 
> library(ellipsis)
> library(devtools)
Loading required package: usethis
> devtools::install_github("boxuancui/DataExplorer", ref = "develop")
Downloading GitHub repo boxuancui/DataExplorer@develop
sh: 1: /usr/bin/gzip: not found
sh: 1: /bin/gtar: not found
sh: 1: /usr/bin/gzip: not found
sh: 1: /bin/gtar: not found
Error: Failed to install 'DataExplorer' from GitHub:
  error in running command
In addition: Warning messages:
1: In system(paste(TAR, "--version >", tf, "2>&1")) :
  error in running command
2: In system(cmd) : error in running command
3: In utils::untar(tarfile, ...) :
  ‘/usr/bin/gzip -dc '/tmp/RtmpLbCjqS/file8f5f5513a1e6.tar.gz' | /bin/gtar -xf '-' -C '/tmp/RtmpLbCjqS/remotes8f5f188ceb02'’ returned error code 127
4: In system(paste(TAR, "--version >", tf, "2>&1")) :
  error in running command

**Comment by statslady** [comment]
It is looking for the gzip, gtar files but where would I find them? Thanks much for your help!

**Comment by boxuancui** [comment]
Could you install from the `master` branch please?

```
devtools::install_github("boxuancui/DataExplorer", ref = "master")
```

**Comment by statslady** [comment]
Hi, I still get the same message after changing the ref value. 
> devtools::install_github("boxuancui/DataExplorer", ref = "master")
Downloading GitHub repo boxuancui/DataExplorer@master
sh: 1: /usr/bin/gzip: not found
sh: 1: /bin/gtar: not found
sh: 1: /usr/bin/gzip: not found
sh: 1: /bin/gtar: not found
Error: Failed to install 'DataExplorer' from GitHub:
  error in running command
In addition: Warning messages:
1: In system(paste(TAR, "--version >", tf, "2>&1")) :
  error in running command
2: In system(cmd) : error in running command
3: In utils::untar(tarfile, ...) :
  ‘/usr/bin/gzip -dc '/tmp/RtmpDoBtc7/file2032486ef156.tar.gz' | /bin/gtar -xf '-' -C '/tmp/RtmpDoBtc7/remotes2032345b2fa5'’ returned error code 127
4: In system(paste(TAR, "--version >", tf, "2>&1")) :
  error in running command

**Comment by boxuancui** [comment]
Hmm. Looks like something is not correctly set up here. What is your OS? Could you make sure those files are in place?

```
sh: 1: /usr/bin/gzip: not found
sh: 1: /bin/gtar: not found
sh: 1: /usr/bin/gzip: not found
sh: 1: /bin/gtar: not found
```

In addition, I just pushed a new version to `master` and `develop` that fixed a dependency problem. I don't think that fixes your problem, but just want to bring it up.

**Comment by statslady** [comment]
I am not sure what these files are. I am in an AWS instance.

**Comment by statslady** [comment]
I am using Windows OS. I am trying this on my own computer. I also restarted the R session. How long does it take to download this package?

**Comment by statslady** [comment]
This seems to have worked finally. I had to update a few packages prior to the install and it was failing because of that. I will test some of the functionality and see if it actually worked.

**Comment by Proloy2018** [comment]
Hi I followed the recommended code but could not install the package (see below). I need your advice please. 

devtools::install_github("boxuancui/DataExplorer", ref = "master")
Downloading GitHub repo boxuancui/DataExplorer@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                 
2: CRAN packages only                  
3: None                                
4: processx   (3.4.4  -> 3.4.5 ) [CRAN]
5: isoband    (0.2.2  -> 0.2.3 ) [CRAN]
6: data.table (1.13.2 -> 1.13.4) [CRAN]

Enter one or more numbers, or an empty line to skip updates:1
ps         (NA     -> 1.5.0 ) [CRAN]
processx   (3.4.4  -> 3.4.5 ) [CRAN]
isoband    (0.2.2  -> 0.2.3 ) [CRAN]
networkD3  (NA     -> 0.4   ) [CRAN]
data.table (1.13.2 -> 1.13.4) [CRAN]
Installing 5 packages: ps, processx, isoband, networkD3, data.table
Installing packages into ‘C:/Users/VALENTINE/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/ps_1.5.0.zip'
Content type 'application/zip' length 763312 bytes (745 KB)
downloaded 745 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/processx_3.4.5.zip'
Content type 'application/zip' length 1379230 bytes (1.3 MB)
downloaded 1.3 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/isoband_0.2.3.zip'
Content type 'application/zip' length 3034447 bytes (2.9 MB)
downloaded 2.9 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/networkD3_0.4.zip'
Content type 'application/zip' length 196667 bytes (192 KB)
downloaded 192 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/data.table_1.13.4.zip'
Content type 'application/zip' length 2582460 bytes (2.5 MB)
downloaded 2.5 MB

package ‘ps’ successfully unpacked and MD5 sums checked
Error: Failed to install 'DataExplorer' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘ps’

**Comment by boxuancui** [comment]
@Proloy2018 Maybe remove `ps` package manually and try again?

**Comment by boxuancui** [comment]
DataExplorer 0.8.2 is on CRAN now. You should be able to install directly from R.

**Comment by statslady** [comment]
Thanks! Do we need to be on a specific version of R and R Studio?

**Comment by boxuancui** [comment]
@statslady You should be able any R version greater than R 3.6.0 and any compatible RStudio version.

**Comment by statslady** [comment]
Thank you very much! Just installed it.

**Comment by Proloy2018** [comment]
Thank you very much. It worked for me too.
