### ISSUE TITLE
Pass theme() info regarding title to the wrap function

### ISSUE THREAD

**Issue by jshousephd** [boxuancui/DataExplorer#152]
I'm enjoying your program a lot!

The following correctly applies theme information to axis.text and axis.title, but not to plot.title.

    plot_bar(discrete[,mystart:myend],
             theme = theme(plot.title = element_text(face = "bold", size = 12),
                           axis.text = element_text(face = "bold", size = 12),
                           axis.title = element_text(face = "bold", size = 12)),
             nrow = 3L, ncol = 3L)

Kind regards

**Comment by boxuancui** [comment]
Hi @jshousephd I am not sure if I am seeing the same problem. After setting the title argument, it is doing what it is supposed to do.

```R
library(ggplot2)
plot_bar(diamonds,
         theme = theme(plot.title = element_text(face = "bold", size = 24),
                       axis.text = element_text(face = "bold", size = 12),
                       axis.title = element_text(face = "bold", size = 12)),
         nrow = 3L, ncol = 3L, title = "My Title")
```

**Comment by jshousephd** [comment]
Sorry, I meant the title of the facets!.  In your case, the size of each plot titles. (cut, color, clarity).



![image](https://user-images.githubusercontent.com/7661058/105765325-44a51e80-5f26-11eb-98af-5ab96a474f4b.png)

**Comment by boxuancui** [comment]
You should be able to customize them using `strip.text`. See detailed information here: https://ggplot2.tidyverse.org/reference/theme.html.

**Comment by jshousephd** [comment]
Thank you so much. Sorry to bother you!
