### ISSUE TITLE
Dependency on R 3.6

### ISSUE THREAD

**Issue by giuseppec** [boxuancui/DataExplorer#153]
I feel that the dependency on R v3.6 is too strict. 
I have seen many companies still having only R 3.5 (or earlier) installed so that I had to remove exercises that are easily solvable with DataExplorer in some courses.
@boxuancui can you maybe describe for which functions R v3.6 is required? 
Maybe the [backports](https://cran.r-project.org/web/packages/backports/index.html) package helps here to go back to a dependency on R v3.5 (or even earlier).

**Comment by boxuancui** [comment]
This is failing a bunch of tests, so I am reverting this back to 3.6: https://github.com/boxuancui/DataExplorer/actions/runs/7617154839/job/20745535065.

> * scales: Needs R >= 3.6
> * testthat: Needs R >= 3.6.0
