### ISSUE TITLE
Is there a way to increase the number of groups / reduce bin width for the boxplot discretization?

### ISSUE THREAD

**Issue by kamaulindhardt** [boxuancui/DataExplorer#157]
**Dear community of experienced DataExplorer users,**

I am having the standard of five groups in the discretized form of my continuous variable, logRR. Is it possible to increase the number of groups, to let's say 7? 

![image](https://user-images.githubusercontent.com/83076278/129524973-ece1aaf5-ad5b-4031-96b6-d1c827c7d012.png)

**Comment by boxuancui** [comment]
You can manually cut your continuous variable into 7 groups and pass it to `by`.
