### ISSUE TITLE
 Insufficient complete rows! Skipping correlation analysis and principal component analysis.

### ISSUE THREAD

**Issue by Shicheng-Guo** [boxuancui/DataExplorer#161]
Hi Boxuan, 

What's the best suggestion to handle the issues below? I am wondering whether we can add imputation before these two analyses? 

## Insufficient complete rows! Skipping principal component analysis.

Thanks

Shicheng

**Comment by boxuancui** [comment]
Hi, I do not plan to add imputation to the package, because it will be misleading to many. I recommend doing a round of imputation before using those functions if necessary. Thanks!
