### ISSUE TITLE
Error: pandoc document conversion failed with error 99

### ISSUE THREAD

**Issue by jfsanch25** [boxuancui/DataExplorer#163]
Estoy tratando de exportar este documento a html pero me sale este error. 

`library(dplyr)
library(readxl)
library(patchwork)
library(ggplot2)

datos <- read_excel("C:\Users\juanf\OneDrive\Escritorio\Estadistica\PROYECTOESTADISTICA")
View(datos)
datos_seleccionados<-select(datos, Peso, Potencia, Coef_Aero, Vel_max )
##View(datos)
matriz_correlacion<-cor(x=datos_seleccionados,method="pearson")#matriz de correlación
View(matriz_correlacion)

p1 <- datos_seleccionados %>%
  ggplot(aes(x=Potencia, y=Peso )) +
  geom_point() + 
  geom_smooth(method="lm", se = FALSE)

p2 <- datos_seleccionados %>%
  ggplot(aes(x=Coef_Aero, y=Peso )) +
  geom_point() + 
  geom_smooth(method="lm", se = FALSE)

p3 <- datos_seleccionados %>%
  ggplot(aes(x=Vel_max, y=Peso )) +
  geom_point() + 
  geom_smooth(method="lm", se = FALSE)

p1 + p2 + p3 

modelo_1<- lm(Peso~Potencia+Vel_max+Coef_Aero, datos_seleccionados)
summary(modelo_1)

#Modelo 1, uníca variable significatiba coef_aero, P valor menor de 0.05. 
#Proponemos otro modelo utilizando la variable ceof_aero relacionada con las otras tres. 

modelo_2<- lm(Coef_Aero~Potencia+Vel_max+Peso, datos_seleccionados)
summary(modelo_2)

#Proponemos un nuevo modelo sub2 eliminando la varibale potencia, pues no es significativa 
#utilizaremos unicamente vel_max y peso, 

modelo_sub2<- lm(Coef_Aero~Vel_max+Peso, datos_seleccionados)
summary(modelo_sub2)
#Vemos la relación que existe entre estas dos variables.

modelo_3<- lm(Vel_max~Potencia+Coef_Aero+Peso, datos_seleccionados)
summary(modelo_3)
#Modelo 3, uníca variable significatiba coef_aero, P valor menor de 0.05. 
#Proponemos otro modelo quitando la variable potencia.

modelo_sub3<- lm(Vel_max~Coef_Aero+Peso, datos_seleccionados)
summary(modelo_sub3)
#Vemos que existe una relación entre las variables.

modelo_4<- lm(Potencia~Vel_max+Coef_Aero+Peso, datos_seleccionados)
summary(modelo_4)
#Modelo 4, Las variables no tienen relacíon entre si.
#Proponemos otro modelo utilizando la variable Potencia relacionada con las otras tres. `
Este es mi codigo, no se si tenga algun error.

**Comment by boxuancui** [comment]
Hi, I don't think this is related to DataExplorer, so closing.
