### ISSUE TITLE
Character conversion problem

### ISSUE THREAD

**Issue by fgardavaud** [boxuancui/DataExplorer#164]
Dear,

I don't find a way to have good conversion when using `plot_correlation` function with special characters in my variables names.

For instance, when I use a dataframe with `(` or `^` in the variable names, these characters are replaced with a dot `.` for each of them.

Here my environment : RStudio 2022.02.0+443 "Prairie Trillium" Release (9f7969398b90468440a501cf065295d9050bb776, 2022-02-16) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36 with R 4.1.2 version.

Perhaps there is a way to correct this behaviour when calling `plot_correlation` function?

**Comment by boxuancui** [comment]
All variable names need to be syntactically valid. See [Make Syntactically Valid Names](https://stat.ethz.ch/R-manual/R-devel/library/base/html/make.names.html). You can pre-treat your column names if you do not like the default `.`. However, they must be syntactically valid for R to process.

**Comment by fgardavaud** [comment]
@boxuancui 
Thks a lot for your quick answer. Yes, I pretreated my names at this stage.
But could it be an enhancement of your great package?

**Comment by boxuancui** [comment]
Hi @fgardavaud thank you for your comment. Is it possible to add support for syntactically invalid names? Possibly yes, but I do not think it is necessary or helpful in any way.

1. Each language has its best practices and I believe it is common for most data practitioners to keep the column names clean and valid. It will not only make your analysis much easier to read, but also save yourself a lot of time debugging unexpected failures from those special characters.
2. As a R user and package maintainer, I believe it is our responsibility to demonstrate good coding practices. In other words, to discourage uncommon or risky ways of using the language. Keeping bad names in `data.frame` is definitely one of them.
3. With all that said, I am sure there are special cases where you absolutely must keep the column names that way. You could always pre-treat your data like what you have been doing. As a package developer, I just can't tweak the infrastructure to support a few edge cases.
4. There are a lot of discussions regarding keeping good names: [here](https://stackoverflow.com/questions/9195718/variable-name-restrictions-in-r), [here](https://cran.r-project.org/doc/FAQ/R-FAQ.html#What-are-valid-names_003f), [here](https://stackoverflow.com/questions/8396577/check-if-character-value-is-a-valid-r-object-name/8396658#8396658).

I hope that helps, and thank you for using DataExplorer!
