### ISSUE TITLE
Plotting twice when knitting to word

### ISSUE THREAD

**Issue by DeLaRiva** [boxuancui/DataExplorer#170]
Hi,
I stumbled over the issue, that when using RMarkdown and knitting to a word file, all DataExplorer plots show up twice ( https://stackoverflow.com/questions/71936921/rmarkdown-knitting-produces-each-plot-twice ).
It doesn't in case of ggplot so I'm relating it to Dataexplorer. However this is caused.

Thanks a lot!

**Comment by boxuancui** [comment]
I believe it is answered on SO, so closing.
