### ISSUE TITLE
Different correlation meters between create_report and plot_correlation

### ISSUE THREAD

**Issue by andresfpatinomd** [boxuancui/DataExplorer#171]
I found that the correlation meters are different between create_report () and plot_correlation() functions. If I run for each pair of continuous variables the cor() or cor.test(), the result of plot_correlation seems to be correct, but the result printed on the correlation plot generated in the create_report file is different.

**Comment by boxuancui** [comment]
The only difference between `plot_correlation` and the one in `create_report` is [`"use" = "pairwise.complete.obs"`](https://github.com/boxuancui/DataExplorer/blob/master/R/configure_report.r#L63), and you can turn it off if you don't want the default setting. Could you double check with your data?
