### ISSUE TITLE
All discrete features ignored! Nothing to plot!

### ISSUE THREAD

**Issue by muzairaslam** [boxuancui/DataExplorer#175]
I am working on creating a report for a data set that has one date time variable and all numeric columns. When I use create_report() it gives :

`label: plot_frequency_bar
Quitting from lines 122-129 (report.rmd) 
Error in (function (data, with = NULL, by = NULL, by_position = "fill",  : 
  Note: All discrete features ignored! Nothing to plot!`

How can I remove this error? I know that this error is due to the absence of categorical columns in the data.

Thanks

**Comment by boxuancui** [comment]
Hi, could you try setting your date time variable to `as.Date()`? The function might have treated it as a categorical variable and ignored it due to [`maxcat`](https://github.com/boxuancui/DataExplorer/blob/master/R/plot_bar.r#L8) constraint.

**Comment by muzairaslam** [comment]
Yes, I removed the date time column from create_report(), and rendered fine. 

Thank you for the help.
