### ISSUE TITLE
Nothing to plot

### ISSUE THREAD

**Issue by shouyongpeng** [boxuancui/DataExplorer#180]
Thanks for this great package! 
Somehow "Error" came out when there is not discrete feature to plot. I would be great to add a line for this condition to skip the plot_bar. 

Error:
! Note: All discrete features ignored! Nothing to plot!
Backtrace:
 1. base::do.call(plot_bar, c(list(data = data), bar_option))
 2. DataExplorer (local) `<fn>`(data = `<dt[,4]>`, ggtheme = theme_gray(), theme_config = `<list>`)

**Comment by boxuancui** [comment]
Hi @shouyongpeng, this error is there [on purpose](https://github.com/boxuancui/DataExplorer/blob/master/R/plot_bar.r#L59) so that users don't end up with bugs that fail silently. If this is disrupting your workflow, please use `tryCatch` to bypass that. Thank you!

**Comment by shouyongpeng** [comment]
> Hi @shouyongpeng, this error is there [on purpose](https://github.com/boxuancui/DataExplorer/blob/master/R/plot_bar.r#L59) so that users don't end up with bugs that fail silently. If this is disrupting your workflow, please use `tryCatch` to bypass that. Thank you!

@boxuancui Thanks for the quick response!

**Comment by boxuancui** [comment]
You are welcome! Thanks for using DataExplorer!
