### ISSUE TITLE
Feature request: report the structure of more complex Objects

### ISSUE THREAD

**Issue by kkoerner** [boxuancui/DataExplorer#33]
At first: I like your package very much, it works perfect for data.frames. 

But I am looking for a functionality to get quick information on more complex Data, as structured lists or multidimensional arrays. What are the names, where are the tables etc.
Or maybe, to report the content of a *.RData file (Data, functions, ...)?

Is it possible to include this in your Package?

**Comment by boxuancui** [comment]
Thank you for your interests, and I am extremely happy to do so.

However, do you mind giving me some concrete examples? For instance, what type of input and output are you expecting? It will be great if you could share some real data, so that I can implement it. If you have privacy concerns to share your data here, feel free to Email me at boxuancui@gmail.com.

Thanks!

**Comment by kkoerner** [comment]
Hi, thank you for your quick response!

Assume, you have a colleague sharing his scientific data with you, and the documentation has its issues. You want to use the data in your scripts, but you don't know exactly how the data structure is and how to access the data you're interested in.

If I got a *.RData or if I have an object, I would like to know:
* wich elements are included (lists, data frames, functions etc.)
* in each case - how big is the data (memory)?
* in case of lists: wich elements are included, and what type are they (list, data.frame, single values etc.)
* recursively analyse these (possibly hierarchical) lists

Pretty much of what I'd like appears in the 'Environment' tab of 'RSudio' or if I use str() or ls.str() with a list. More nicely formatted and condensed for large sub-elements or repititive structures it would be perfect in an html document..
Ill append an example:

[example.zip](https://github.com/boxuancui/DataExplorer/files/611264/example.zip)

Sincerely

kkoerner

**Comment by boxuancui** [comment]
Please install the latest develop version: `devtools::install_github("boxuancui/DataExplorer", ref="develop")`, and refer to `?PlotStr` for this issue. You might want to do `PlotStr(case0, max_level = 2)` or `PlotStr(case0[[1]])` to reduce the output size. Let me know if you have any comments/questions.
