### ISSUE TITLE
Add function to customize report

### ISSUE THREAD

**Issue by boxuancui** [boxuancui/DataExplorer#41]
- Pick what to appear in report.
- Able to customize each chart.

**Comment by boxuancui** [comment]
Might be able to customize report through

	rmarkdown::render(
		...,
		params = list(
			data = data,
			report_configuration = list() ## function name should be the key and associated arguments should be the list value
		)
	)

**Comment by leppott** [comment]
I added the following into the YAML header to get date/time and author of the report. 

author: "`r Sys.getenv('USERNAME')`"
date: "`r Sys.time()`"
