### ISSUE TITLE
Fix color scale for correlation plots

### ISSUE THREAD

**Issue by boxuancui** [boxuancui/DataExplorer#47]
Reported by @Raelili :

The color scale for correlation heat map looks misleading sometimes. For example, a -0.8 correlation looks less correlated than a 0.1 correlation. The color scale should be fixed to either [-1, 1] or the maximum of both absolute values.

**Comment by Raelili** [comment]
haha

你居然听取了我的建议！

**Comment by boxuancui** [comment]
@Raelili Do you want to try fixing it? If so, feel free to submit a pull request.
