### ISSUE TITLE
Fix misleadingness in vignette

### ISSUE THREAD

**Issue by boxuancui** [boxuancui/DataExplorer#55]
As pointed out by @peSHIr [here](http://blog.revolutionanalytics.com/2018/02/dataexplorer.html#comment-6a010534b1db25970b01b8d2d89f95970c), the data needs to be cleaned before grouping.

> The vignette aircraft examples are a bit misleading, as data needs a bit more cleanup, I think. Airbus is in the list with two different strings, McDonnell Douglas with at least three, and Canada with two. If those were first lumped together into one each, before lumping the long tail together into an "other" bin, this could make a big difference in further modeling, as Airbus would jump to largest group by far, not the third, with about half of the Airbus data being lumped into "other". #oops

**Comment by peSHIr** [comment]
Never thought at the time to add this as an issue on github myself. Thanks for taking the time to find me on here and link to me. Kudos.
