### ISSUE TITLE
Themes to plots

### ISSUE THREAD

**Issue by amrrs** [boxuancui/DataExplorer#56]
Is it possible to add themes to existing plot outputs?

**Comment by boxuancui** [comment]
Do you mean [these](http://ggplot2.tidyverse.org/reference/ggtheme.html)?

**Comment by holgerbrandl** [comment]
Along with that: theming should be consistent between plots. Currently boxplots are using the default ggplot2 theme, but barplots do not.

**Comment by sugang** [comment]
I also recommend adding a parameter to let users specify the size of fonts. For plot_missing on large datasets the axis and label texts are barely legible. Actually I feel it would be more useful to return the chart than return the data table so that users may do additional processing w/ the charts

**Comment by boxuancui** [comment]
@sugang Do you mind creating a separate issue for your comment? While this issue should be a quick fix, your suggestion might require some major infrastructure change. I do not want to lose sight of it, and I need to think about it a little. Thanks!

**Comment by boxuancui** [comment]
@sugang While I use `theme_set()` to resolve this issue, I will try to include `theme_update()` or `theme_replace()` to allow changes to individual elements, e.g., font size.

**Comment by sugang** [comment]
Sure. I check the source code and the values are fixed at the moment. I have some other recommendations, will create tickets.
