### ISSUE TITLE
function to plot all X against y

### ISSUE THREAD

**Issue by wwells** [boxuancui/DataExplorer#58]
Thank you for your great work on this package!   One enhancement that may be worth considering is a common EDA effort in regression or supervised learning - plot all X against the Y (all independant variables against the dependant one).   

There are plenty of examples out there for how to accomplish this task as part of an EDA, but it's a pretty common task, so may be useful to the DataExplorer community.

Something like: 
<img width="638" alt="screen shot 2018-02-17 at 10 51 23 am" src="https://user-images.githubusercontent.com/5175497/36343342-943f57c0-13d0-11e8-908b-75b874afb571.png">

Cheers and thanks again!

**Comment by boxuancui** [comment]
@wwells Have you checked out the function [`plot_scatterplot`](https://github.com/boxuancui/DataExplorer/blob/master/R/plot_scatterplot.r) from the package? I think it does exactly what you are asking for. Example code:

    plot_scatterplot(data, "Wins")

Note: discrete and continuous features are plotted on separate pages.

**Comment by wwells** [comment]
ah - indeed!   Thanks and kudos.
