### ISSUE TITLE
CRAN mirror problem

### ISSUE THREAD

**Issue by cardosop** [boxuancui/DataExplorer#60]
Hello,

I was trying to install the library earlier today directly from the CRAN mirror but after installing I couldn't load the library, error message:
Error: package or namespace load failed for ‘DataExplorer’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘rprojroot’

Then I downloaded through the github repository and worked well.

Thank you for the library!

**Comment by boxuancui** [comment]
Would you mind providing more information for that problematic session? e.g.,

1. Delete current DataExplorer package.
1. Install DataExplorer from CRAN.
1. If the same error message comes back, could you paste the output of `devtools::session_info()`?

I was looking at the reverse dependency of **rprojroot**, and the only intersecting package is **rmarkdown**. Could you also share the version of your **rmarkdown**?

**Comment by cardosop** [comment]
Hi,

I had identified the issue root cause, it's not related to the package. My McAfee updated and now is not letting me install any library automatically.

Sorry for bother and thank you for the awesome package.

**Comment by boxuancui** [comment]
No worries! Thank you for using DataExplorer!
