### ISSUE TITLE
error namespace ‘data.table’ 1.10.4 is being loaded, but >= 1.10.4.3 is required

### ISSUE THREAD

**Issue by nujcharee** [boxuancui/DataExplorer#61]
Hi there
I just installed R version 3.4.4 and DataExplorer library, when tried to load the library I got an error below.
I am on windows, 64 bits.

```
Error: package or namespace load failed for ‘DataExplorer’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘data.table’ 1.10.4 is being loaded, but >= 1.10.4.3 is required
```

Thank you

**Comment by boxuancui** [comment]
Please update your data.table package to version 1.10.4.3 or later. This should fix the problem.
