### ISSUE TITLE
plot_histogram/plot_density will fail whenever there are spaces in column names

### ISSUE THREAD

**Issue by litaxc** [boxuancui/DataExplorer#63]
If any of the column name in the dataset contains a white space, `plot_histogram` and `plot_density` will fail.
It could be fixed by altering the column names before feeding into the function.

Here's the full error message: `Life Ladder` is the first column in my dataset appeared containing a white space in it.
```
Error in parse(text = x): <text>:1:6: unexpected symbol
1: Life Ladder
         ^
Traceback:

1. plot_histogram(whr_2018)
2. lapply(seq_along(subset_data), function(j) {
 .     x <- na.omit(subset_data[, j, with = FALSE])
 .     ggplot(x, aes_string(x = names(x))) + geom_histogram(bins = 30L, 
 .         colour = "black", alpha = 0.4, ...) + scale_x_continuous(labels = comma) + 
 .         scale_y_continuous(labels = comma) + ylab("Frequency")
 . })
3. FUN(X[[i]], ...)
4. ggplot(x, aes_string(x = names(x)))
5. ggplot.data.frame(x, aes_string(x = names(x)))
6. inherits(mapping, "uneval")
7. aes_string(x = names(x))
8. lapply(mapping, function(x) {
 .     if (is.character(x)) {
 .         parse(text = x)[[1]]
 .     }
 .     else {
 .         x
 .     }
 . })
9. FUN(X[[i]], ...)
10. parse(text = x)
```

I am not very experienced in r functional programming, but I would like to help if there's any I could.

**Comment by boxuancui** [comment]
Thanks for reporting. It is fixed with commit 62a1046. Please install the latest `develop` branch, e.g., `remotes::install_github("boxuancui/DataExplorer", ref = "develop")`
