### ISSUE TITLE
Show missing values in categorical plots

### ISSUE THREAD

**Issue by Aylr** [boxuancui/DataExplorer#67]
While I find the Missing Values plot extremely valuable, I often want to compare the amount missing for a given column with the existing values. This way an analyst can understand both the distribution of actual values and how it compares to the amount of missing values without needing to refer to two separate graphs, all with reduced cognitive overhead.

For example:

<img width="667" alt="screen shot 2018-05-07 at 12 35 31 pm" src="https://user-images.githubusercontent.com/928247/39718370-533bddb4-51f3-11e8-85d0-69e9bff826ae.png">

I'm happy to take a shot at this if you agree.

**Comment by boxuancui** [comment]
If you use the latest [develop version](https://github.com/boxuancui/DataExplorer/tree/develop) of `plot_bar`, it should have exactly what you need.

    df <- data.frame("a" = c(rep("a", 15), rep(NA_character_, 5)))
    plot_bar(df$a)

Alternatively, if you would like to stick to current stable version, you can simply do

    plot_bar(df$a, na.rm = FALSE)

**Comment by boxuancui** [comment]
If you have what you need, please close this. Thanks!
