### ISSUE TITLE
create_report in PDF form fails from within HTML R Notebook

### ISSUE THREAD

**Issue by kmishra9** [boxuancui/DataExplorer#68]
Hey there, 

I have an R notebook with the following YAML header:
```
---
title: "Data Import, Cleaning, Merging, and Export"
output: html_notebook
---
```
Here's my traceback, ending with the original call to `create_report()`:
![snip20180526_3](https://user-images.githubusercontent.com/10662252/40574922-18ba92ba-6090-11e8-9ee8-b39d32e330bc.png)

In addition, I wasn't able to find very much informative information on simply how to generate PDF reports, so that may have some bearing on running into this issue

**Comment by boxuancui** [comment]
Try changing output format:

    DataExplorer::create_report(..., output_format = "pdf_document")

**Comment by kmishra9** [comment]
I unfortunately still run into an issue after changing my Notebook's YAML heading as specified:
```
---
title: "Data Import, Cleaning, Merging, and Export"
output: html_notebook
always_allow_html: yes
---
```

![image](https://user-images.githubusercontent.com/10662252/40591717-fbed3d2c-61ca-11e8-8fc8-2361be4a978b.png)

**Comment by boxuancui** [comment]
I believe you have to change your output in the YAML as well. See [this](https://github.com/rstudio/rmarkdown/pull/559).

The error is generated from this [code](https://github.com/rstudio/rmarkdown/blob/master/R/render.R#L530-L550). A reminder is that any HTML dependencies will be ignored. See [this](https://github.com/rstudio/rmarkdown/issues/516). Do you have to create the report in PDF format?

**Comment by boxuancui** [comment]
@kmishra9 Did this work?

**Comment by kmishra9** [comment]
Hey there, so some context — 

Having it in PDF format makes it a little easier to share and PDFs render within GitHub repos while HTML reports need to be downloaded then opened. These reports are also being generated on an isolated EC2 server so syncing them via Git would be optimal over other methods. I haven’t had a chance to test the solution you provided as I’m traveling right now with very limited internet access but will report back eventually! 

Another issue I’m running into is relatively high memory usage. I have a 2GB file with a bit over a million rows and around 20 columns, and generating a report on that was unsuccesful on an m5.large instance (4 CPUs, 8GB of RAM, and 30GB of swap). Generating the report required roughly 15-20GB of RAM and so a suggestion for you (and something I’d even be interested in helping contribute to, once I get my head above the water), is engineer some sort of caching system where reports store results of plots in temp files in an SSD and have a final step of report generation be linking all those together. This would have a couple of advantages 1) suitable for bigger datasets — this is great where there is a large amount of data and possibly creating a report takes a while. Interrupts for whatever reason wouldn’t be as big of a deal if progress was cached and could be resumed based on whatever needed to still be plotted before aggregation. 2) Going off this, it could be far more efficient for new report generation if the data was only replotted if the data had changed. Keeping like an MD5 hash of the column of data along with the intermediate hidden metadata would not take very long but could also help speed things up — if the data is unchanged, the plot will be as well. Anyways, good things to think about if you want to continue to improve what is already a very useful package! 

I’ll report back on the fix when I get a chance!

**Comment by kmishra9** [comment]
Some corrections — the dataset was 4.4 GB, with 61 million rows and about a billion data points. So I noticed the following and resized up to an instance with drastically more memory once I realized the lack of RAM was limiting what the CPU could do (it was waiting for RAM to be paged to disk and back and that’s just super slow). At one point, R was using 50+ GB of RAM for this dataset (which is problematic for all of the reasons outlined in the above post).

Once I had resized up to an instance with much more RAM, the report took about 20 minutes to generate (vs. 24+ hours on an instance with 8GB — I stopped it after about 24), making the above points somewhat of a dire need as big data becomes more and more prevalent, as not many R users have the know how or access to supercomputing servers.

![6dc90aec-dff5-40eb-95a2-000aa2d1a77c](https://user-images.githubusercontent.com/10662252/40755141-5a23026e-647d-11e8-950b-2b3662b8b967.png)


One final observation that may be helpful from an optimization perspective — it doesn’t appear that objects and whatnot were freed up from memory after they were used (check of the `gc()` command if you’re unfamiliar with garbage collection). After each plot is created, the actual plot itself should be rather small and easy to fit in RAM, but there appears to be some sort of issue where the things in RAM  stay there while new plots and eveything needed to fit them are deposited in very slow swap memory. I’m not quite sure why this is — its rather nonintuitive, since things that are not needed anymore should be moved to slow swap and displaced by the things under active computation (for example, when plotting histograms, the plot misssing plot stuff should be moved to swap if I run out of RAM, and computation should proceed at a fairly quick pace. What instead seems to be happening is that when plotting histograms, everything from plotting histograms is left in slow swap and everything from plotting missing values remains in RAM where that extra speed is unnecessary since its not being computed on anymore. Something to potentially think about if you make any optimizations!

**Comment by boxuancui** [comment]
All valid points, but my two-cents here:

1. `rmarkdown` and `knitr` has some caching parameters. I will certainly investigate if applicable.
1. I agree that RAM usage for big data is a problem, but may not be a priority or direction for this package. Here is why:
    * The intention of `create_report` is to be used after all EDA processes. After that, big messy data should be cleaned and reduced, so that resources could be freed from all the anomalies and messiness. In the latest release, I have also added report customization, so that you can pick what is relevant for your report. That could also reduce RAM usage and build time.
    * I do not think hardware issue is a problem these days. As you said, by throwing a beefier machine at it, it should just work. With platforms like AWS, this is even easier.
    * Have you set appropriate classes to each feature? This somehow duplicates my first bullet, but setting the right class could potentially save a lot of resources.
    * You may find some insights from [here](https://github.com/rstudio/rstudio/issues/2319).
    * However, with all that said. I am not rejecting the idea of optimization and resource management. Just that this is not a priority for now.
1. I welcome all comments and suggestions, but would like to keep each issue independent. Since the original ask is about rendering PDF, could we keep on communicating that in here? Feel free to create a separate issue to share your ideas.
