### ISSUE TITLE
DataExplorer install.packages

### ISSUE THREAD

**Issue by sergedahdouh** [boxuancui/DataExplorer#73]
hey I tried to install DataExplorer package and I always have the 0.4.0 version instead of last version 0.60. and when I am trying to use  if (!require(remotes)) install.packages("remotes")
remotes::install_github("boxuancui/DataExplorer") I always receive an installation of package had non-zero exit status so please I need help.

**Comment by boxuancui** [comment]
Could you copy & paste the entire error message here?

Could you also provide the output of this?

    sessionInfo()

**Comment by sergedahdouh** [comment]
Thank you for your reply.

Fortunately, I solved the problem.

**Comment by boxuancui** [comment]
OK.

I still recommend you installing the latest version from master, because I fixed a [bug](https://github.com/boxuancui/DataExplorer/issues/69) for `create_report`.

    remotes::install_github("boxuancui/DataExplorer")

Otherwise, thanks for using DataExplorer!
