### ISSUE TITLE
R DataExplorer package - Cannot use functions

### ISSUE THREAD

**Issue by Kallikrates** [boxuancui/DataExplorer#79]
I successfully installed R 'DataExplorer' package using RStudio, but when I go to use functions from this package, I'm getting errors.

> Error: could not find function "plot_missing" Error: could not find function "create_report"

I downloaded from GitHub:

    if (!require(remotes)) install.packages("remotes")
    remotes::install_github("boxuancui/DataExplorer")

Any suggestions as to why? Thank you!

Below are my particulars:

> platform x86_64-w64-mingw32
> arch x86_64
> os mingw32
> system x86_64, mingw32
> status
> major 3
> minor 3.2
> year 2016
> month 10
> day 31
> svn rev 71607
> language R
> version.string R version 3.3.2 (2016-10-31) nickname Sincere Pumpkin Patch

**Comment by aakbarie** [comment]
You need to load the package to use it first!!!!!!!!!!!!!

    library(DataExplorer)

**Comment by Kallikrates** [comment]
@aakbarie I have loaded it. Hence my concern.

**Comment by boxuancui** [comment]
@Kallikrates Could you take a look at [this link](https://stackoverflow.com/questions/7027288/error-could-not-find-function-in-r#)?

Could you also load the package and paste the output of `sessionInfo()`?

**Comment by Kallikrates** [comment]
Hi. Do you mean to say you closed it because it was posted on SO as well as
GH? Apologies - I didn't know you couldn't. And will do - cheers.

**Comment by Kallikrates** [comment]
Not sure what happened, but this is now working. Closing
