### ISSUE TITLE
Possible failure to escape variable names

### ISSUE THREAD

**Issue by rodzam** [boxuancui/DataExplorer#81]
**Issue:** DataExplorer does not properly escape variable names when given as a string in an argument.

**Example:**
```R
df1 <- tibble(population=c(10,20,30,40,50), `poverty-rate`=c(50,40,30,20,10), `pct-hisp`=c(.2,.5,.3,.2,.6))
plot_scatterplot(df1, by="poverty-rate")
```
**Error:**

> Error in FUN(X[[i]], ...) : object 'poverty' not found

I expect it's a simple issue where the function isn't properly escaping the variable name (e.g., \`poverty-rate\`). As an aside, I'd agree that it's bad practice to include mathematical operators in the variable name but sometimes an external dataset will use that nomenclature so we must work with it.

**Comment by boxuancui** [comment]
Working with irregular names is not easy, and creates a lot of potential problems. End users should supply appropriate names because it is so much easier to do so. E.g.,
```R
names(df1) <- make.names(names(df1))
plot_scatterplot(df1, by = "poverty.rate")
```
As a result, I am closing this.
