### ISSUE TITLE
Histogram axis ranges

### ISSUE THREAD

**Issue by pat-s** [boxuancui/DataExplorer#82]
Are hardcoded currently.

https://github.com/boxuancui/DataExplorer/blob/f539a689411c75f3925d6c5976101789c4d827f1/R/plot_histogram.r#L64-L65

This leads to undesired behavior in histograms for variables with only 1 digit.

Given the fact that the ggplot objects are not returned, its not possible to change it. Looking forward to v0.7 :)

Reprex:

``` r
d = OpenML::getOMLDataSet(data.id = 61)
#> Downloading from 'http://www.openml.org/api/v1/data/61' to '/tmp/Rtmp1elTLE/cache/datasets/61/description.xml'.
#> Downloading from 'https://www.openml.org/data/v1/download/61/iris.arff' to '/tmp/Rtmp1elTLE/cache/datasets/61/dataset.arff'
#> Loading required package: readr

# convert the OpenML object to a tibble (enhanced data.frame)
iris = tibble::as_tibble(d)

DataExplorer::plot_histogram(iris, ggtheme = ggpubr::theme_pubr())
```

![](https://i.imgur.com/h61Qid9.png)

<sup>Created on 2018-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by boxuancui** [comment]
Removed almost all hard-coded scales from all plot functions.

**Comment by pat-s** [comment]
Cool, thanks!
