### ISSUE TITLE
Can it handle larger-than-RAM data?

### ISSUE THREAD

**Issue by xiaodaigh** [boxuancui/DataExplorer#93]
If not then I am super interested in connecting [disk.frame](https://github.com/xiaodaigh/disk.frame) to this

**Comment by boxuancui** [comment]
Yes, you should be able to pass `data.table` objects directly.

**Comment by xiaodaigh** [comment]
@boxuancui but data.table holds data in RAM. Ideally, we should be able to pass in a part of the data, summarise that, then pass in another part etc so we don't have to pass in the data all in one go as RAM may not be able to hold all the data.

**Comment by boxuancui** [comment]
Apologies, I don't think I made myself clear. I looked at [disk.frame README](https://github.com/xiaodaigh/disk.frame/blob/master/README.md) and saw:

> In contrast, disk.frame makes use of data.table::data.table and data.frame directly, so all data types are supported.

DataExplorer is using data.table at the backend as well, so I think you should be able to pass disk.frame objects. Feel free to try it and let me know if it works.
