### ISSUE TITLE
Support for other output document type?

### ISSUE THREAD

**Issue by JiaxiangBU** [boxuancui/DataExplorer#96]
I think the output format like `github_document` or `md_document` is easy to represent on Github.

**Comment by boxuancui** [comment]
Just to make sure, this is for the output file from `create_report` right?

**Comment by JiaxiangBU** [comment]
> Just to make sure, this is for the output file from `create_report` right?

Yes, `create_report` now is available for `html_document`.

**Comment by boxuancui** [comment]
After some investigation, you can just pass `output_format` to `create_report`, since that will be passed along to `render` through `...`. However, some of the output format might not work due to the JavaScript elements. I tested `md_document` without `plot_str`, and it is working fine.
