### ISSUE TITLE
plot_str not rendering with R Shiny

### ISSUE THREAD

**Issue by aagarw30** [boxuancui/DataExplorer#97]
Hello,
I am trying to plot the structure of my dataset using the `plot_str()`.
The function works well when I use in R console however when integrated with R Shiny it does not show up the plot.

Here is the reproducible example. Not sure if I am making a mistake or rendering incorrectly.

```R
library(shiny)
library(DataExplorer)

ui <- fluidPage(
  plotOutput("plot")
)

server <- function(input, output, session) {
  output$plot <- renderPlot({
    print(plot_str(iris))
  })
}

shinyApp(ui, server)
```

Additionally, I am running this in WIN OS, `str_intro()` renders perfectly in R Shiny.

> sessionInfo()
> R version 3.4.4 (2018-03-15)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_India.1252  LC_CTYPE=English_India.1252   
> [3] LC_MONETARY=English_India.1252 LC_NUMERIC=C                  
> [5] LC_TIME=English_India.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] randomForest_4.6-14  DiagrammeR_1.0.0     rpart.plot_3.0.6    
>  [4] rpart_4.1-13         DataExplorer_0.7.0   DT_0.4              
>  [7] shinyjs_1.0          shinyBS_0.61         shinydashboard_0.7.0
> [10] shiny_1.0.5          caret_6.0-81         ggplot2_3.0.0       
> [13] lattice_0.20-35     

Thanks in advance for help.

**Comment by aagarw30** [comment]
Forgot to mention that I have tried rendering with and without `print()` but no success.

```R
output$plot <- renderPlot({
  print(plot_str(iris))
})

output$plot <- renderPlot({
  plot_str(iris)
})
```

**Comment by boxuancui** [comment]
Have you tried `diagonalNetworkOutput` in ui and `renderDiagonalNetwork` in server? These plots are sourced from `networkD3` package.

**Comment by aagarw30** [comment]
Hello,
No, let me try them and confirm the outcome. Thanks for feedback.

Ty Abi

**Comment by aagarw30** [comment]
Hello,

I tried the recommendation however still not showing up the plot in the app. Could you please review and help?

Updated and reproducible code as follows:

```R
library(shiny)
library(DataExplorer)
library(networkD3)

ui <- fluidPage(
  diagonalNetworkOutput("plot")
)

server <- function(input, output, session) {
  output$plot <- renderDiagonalNetwork({
    plot_str(iris)
  })
}

shinyApp(ui, server)
```

**Comment by boxuancui** [comment]
I was able to run your code and see the plot.

Could you try the following?

```R
library(shiny)
library(DataExplorer)
library(networkD3)

ui <- fluidPage(
  diagonalNetworkOutput("plot")
)

server <- function(input, output, session) {
  output$plot <- renderDiagonalNetwork({
    str_list <- plot_str(iris, print_network = FALSE)
    diagonalNetwork(str_list)
  })
}

shinyApp(ui, server)
```

**Comment by aagarw30** [comment]
Thanks so much !
Tested and working fine now.
This can be closed.
Appreciate help and support in this matter.
ty Abi

**Comment by boxuancui** [comment]
Thanks for using DataExplorer!
