### ISSUE TITLE
changing plot_missing threshold classification

### ISSUE THREAD

**Issue by prvst** [boxuancui/DataExplorer#98]
Is it possible to change the plot_missing threshold classification ? I work with data sets which 2% missing is already bad, but when I plot them using plot_missing it says that they are good. The plots are not for me, so this might confuse some people.

**Comment by boxuancui** [comment]
As a temporary solution, you can hack [`profile_missing`](https://github.com/boxuancui/DataExplorer/blob/master/R/profile_missing.r#L29-L32) and [`plot_missing`](https://github.com/boxuancui/DataExplorer/blob/master/R/plot_missing.r#L25) function by tweaking the threshold.

**Comment by prvst** [comment]
Thanks
nice job with this package btw.

**Comment by boxuancui** [comment]
@prvst I still plan to put something in place for end users to customize the threshold. However, I do not have a good idea at this moment. I am re-opening, so that it doesn't disappear off the radar.

**Comment by prvst** [comment]
cool, thanks for the quick reply

**Comment by boxuancui** [comment]
@prvst With the latest `develop` branch, you can customize the band.

Example:
```R
plot_missing(airquality, group = list("B1" = 0, "B2" = 0.06, "B3" = 1))
```
